In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
import networkx as nx
import random
import pickle
import itertools
import math
import urllib.request as urllib
import io
import zipfile

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import layers, losses
from tensorflow.keras.models import Model
from tensorflow.linalg import diag
from tensorflow.keras import callbacks
from sklearn.cluster import KMeans
from sklearn.metrics.cluster import normalized_mutual_info_score
from networkx.generators.community import LFR_benchmark_graph
from itertools import count
from scipy.spatial import distance_matrix
from sklearn.decomposition import NMF
from rdyn import RDyn

from helpers import *
from Autoencoder import *

In [2]:
graphlist = pickle.load(open('graphs/thiers_day_19.p', 'rb'))

In [37]:
#DAY 19, SNAPSHOT 1
t1 = graphlist[0]
A = create_adjacency_matrix(t1)
t1_A = tf.convert_to_tensor(create_adjacency_matrix(t1).astype('float32'))
t1_B = tf.convert_to_tensor(nx.modularity_matrix(t1).astype('float32'))
t1_S = tf.convert_to_
t1_L_norm = tf.convert_to_tensor(create_normalized_laplacian(t1_A))

ZeroDivisionError: float division by zero

In [38]:
create_degree_matrix(t1_A)

array([[2., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 2., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [4]:
t1_model_1 = Autoencoder(174, 128, k_reg=tf.keras.regularizers.L2(), act_reg=SparseRegularizer())
t1_model_1_history = train(t1_model_1, 5000, 174, t1_B)

In [6]:
#encoding
t1_model_1_H = t1_model_1.encoder(t1_B)

In [29]:
#try sharing weights
t1_model_1_v2 = Autoencoder(174, 128, k_reg=tf.keras.regularizers.L2(), act_reg=SparseRegularizer())
temp = t1_model_1_v2.predict(t1_B)
t1_model_1_v2.history = {}
t1_model_1_v2.set_weights(t1_model_1.get_weights())
t1model1v2_history = train(t1_model_1_v2, 1000, 1000, t1_A)

In [34]:
train(t1_model_1_v2, 4000, 1000, t1_A)

{0: <tf.Tensor: shape=(), dtype=float32, numpy=0.0005947824>,
 1: <tf.Tensor: shape=(), dtype=float32, numpy=0.0005947291>,
 2: <tf.Tensor: shape=(), dtype=float32, numpy=0.00059467606>,
 3: <tf.Tensor: shape=(), dtype=float32, numpy=0.0005946233>,
 4: <tf.Tensor: shape=(), dtype=float32, numpy=0.000594571>,
 5: <tf.Tensor: shape=(), dtype=float32, numpy=0.0005945187>,
 6: <tf.Tensor: shape=(), dtype=float32, numpy=0.00059446687>,
 7: <tf.Tensor: shape=(), dtype=float32, numpy=0.00059441477>,
 8: <tf.Tensor: shape=(), dtype=float32, numpy=0.0005943632>,
 9: <tf.Tensor: shape=(), dtype=float32, numpy=0.00059431157>,
 10: <tf.Tensor: shape=(), dtype=float32, numpy=0.00059426005>,
 11: <tf.Tensor: shape=(), dtype=float32, numpy=0.00059420866>,
 12: <tf.Tensor: shape=(), dtype=float32, numpy=0.0005941575>,
 13: <tf.Tensor: shape=(), dtype=float32, numpy=0.00059410604>,
 14: <tf.Tensor: shape=(), dtype=float32, numpy=0.00059405476>,
 15: <tf.Tensor: shape=(), dtype=float32, numpy=0.00059400

In [36]:
H = t1_model_1_v2.encoder(t1_A)
labels = graph_labels(t1)
kmeans = KMeans(n_clusters=5, n_init=20).fit(H)

normalized_mutual_info_score(labels, kmeans.labels_)

0.09357173404929846

In [13]:
H_1 = model_t1.encoder(t1_B)
model_t1_2 = Autoencoder(128, 64, k_reg=tf.keras.regularizers.L2(), act_reg=SparseRegularizer())
history_t1_2 = train(model_t1_2, 1000, 174, H_1)

In [9]:
H

<tf.Tensor: shape=(174, 128), dtype=float32, numpy=
array([[0.54173803, 0.54363394, 0.54413784, ..., 0.5443968 , 0.5423584 ,
        0.5440059 ],
       [0.5417582 , 0.5416691 , 0.540448  , ..., 0.5424734 , 0.54326904,
        0.541846  ],
       [0.5406985 , 0.54145163, 0.5412723 , ..., 0.5423385 , 0.5437761 ,
        0.543375  ],
       ...,
       [0.5420168 , 0.54230314, 0.54172015, ..., 0.5424788 , 0.5423876 ,
        0.5428387 ],
       [0.5420168 , 0.54230314, 0.54172015, ..., 0.5424788 , 0.5423876 ,
        0.5428387 ],
       [0.5420168 , 0.54230314, 0.54172015, ..., 0.5424788 , 0.5423876 ,
        0.5428387 ]], dtype=float32)>

In [24]:
t1_S[16]

<tf.Tensor: shape=(174,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.], dtype=float32)>